project:
  type: website

website:
  title: "Zach Wagner"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - file: Research.qmd
        text: "Research"
      - file: Teaching.qmd
        text: "Teaching"
      - file: Blog.qmd
        text: "Blog"

  sidebar:
    -title: "Blog"
    style: "floating"
    search: true
    contents:
      - section: "Blog"
        contents: Blog/*

  search:
    location: navbar
    type: textbox

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



