---
title: "Restricting the Dirac-Fock energy to the Electron Subspace"
description: "A variational method to solving the Dirac-Fock equations when restricted to the subspace induced by the positive spectral projector of the dirac operator."
author: "Zach Wagner"
date: "11/05/2023"
categories:
  - Functional Analysis
  - Partial Differential Equations
bibliography: Restricting Dirac Fock Refs.bib
draft: false
---

The Dirac-Fock energy functional is the relativistic counterpart to the Hartree-Fock energy functional, and acts on four-component square integrable wave functions which arise from Slater determinants. This ensures the wave functions satisfy the particle statistics we expect from fermions. In normal atomic units, the Dirac-Fock energy $\mathcal{E}$ acts on an $N$ electron wave function $\psi\in H^{1/2}(\mathbb{R}^3;\mathbb{C}^4)\wedge ...\wedge  H^{1/2}(\mathbb{R}^3;\mathbb{C}^4)$ via [@esteban_solutions_1999],

$$\mathcal{E}(\psi):=\sum_{j=1}^N\left((\psi_j,D\psi_j)-\alpha Z\left(\psi_j,\frac{1}{|x|}\psi_j\right)\right)$$

$$+\frac{\alpha}{2}\int\int_{\mathbb{R}^3\times\mathbb{R}^3}\frac{\rho(x)\rho(y)-\text{tr}(R(x,y)R(y,x))}{|x-y|}dydx$$

Here, $(\cdot,\cdot)$ is the $L^2$ inner product, $\rho(x)$ is the usual particle density and $R(x,y)=\sum_{j=1}^N\psi_j(x)\otimes\psi_j(y)^*$ (the star denoting conjugate transpose). $\alpha$ is the fine structure constant, $Z$ is the nuclear charge, and $D$ is the Dirac operator in normal atomic units. Critical points of $\mathcal{E}$ solve the Dirac-Fock equations, which is an eigenvalue problem when an $L^2$ constraint (typically norm one) is imposed.

## Spectral Projections

The Dirac operator has purely absolutely continuous spectrum $\left(-\infty, -1\right]\cup \left[1,\infty\right)$. This is the primary source of numerical difficulties in dealing with functionals such as $\mathcal{E}$, which is not bounded from below. A possible means to correct this is as follows: $D$ induces spectral projectors which take the form [@thaller_dirac]:

$$P^{\pm}=\frac{1}{2}\left(1\pm\frac{D}{|D|}\right)$$

The Hilbert space $H^+:=P^+L^2(\mathbb{R}^3;\mathbb{C}^4)$ denotes the positive spectral subspace, which corresponds to the "electron subspace." In a sense, the orthogonal complement to this space denotes the space of positrons, and it is this mathematics that first led physicists to conjecture the existence of positrons. On $H^+$, we have $(\psi,D\psi)>0$ and in fact when $\psi\in H^{1/2}(\mathbb{R}^3;\mathbb{C}^4)$, we have $||\psi||_{H^{1/2}}^2=(\psi,D\psi)$. Let $H:=P^+H^{1/2}(\mathbb{R}^3;\mathbb{C}^4)$. By Kato's inequality, one easily sees that $\mathcal{E}$ is bounded below when restricted to $H$. Thus, since the electron subspace is presumably the physically interesting space to us, it is natural to minimize $\mathcal{E}$ on $H$.

## Sketch of the Minimization Procedure

The procedure here follows the same ideas as in [@lieb_hartree-fock_nodate]. We've already mentioned that $\mathcal{E}$ is bounded below on $H$, which follows from Kato's inequality for $\psi\in H$:

$$(\psi,V\psi)\leq K(\psi,D\psi)$$

($K=\frac{\pi}{4}+\frac{1}{\pi}$) and the fact that we have the estimate [@esteban_solutions_1999],

$$\int\int_{\mathbb{R}^3\times\mathbb{R}^3}\frac{\rho(x)\rho(y)}{|x-y|}dydx\leq NK(\psi, D\psi)$$

In particular, one has the estimate,

$$\mathcal{E}(\psi)\geq \left(1-\alpha Z\right)\sum_{j=1}^N||\psi_j||_{H^{1/2}}^2$$

which is positive with suitable restrictions on $Z$. Hence, given a minimizing sequence $\psi_n\in H$ with $||\psi_n||_2\leq 1$ for $\mathcal{E}$, we have a weakly convergent subsequence $\psi_n\rightharpoonup \psi$ in $H$. The goal is to show that $\psi$ is, in fact, the solution to the minimization problem and that $\psi$ is of unit norm. Relaxing a minimization problem in this sense (that is, assuming $||\psi_n||_2\leq 1$) is common in the literature, as one can often prove readily after getting a solution that the minimizing function does have the desired norm. 

Lower-semicontinuity of $\mathcal{E}$ actually follows fairly readily, giving us a minimizer. Given $\varphi_n\rightharpoonup 0$, we actually have [@coti_zelati_ground_2019] $(\varphi_n,V\varphi_n)\rightarrow 0$, so combining this, Kato's inequality, and weak lower-semicontinuity of the norm yields weak lower-semicontinuity of $\mathcal{E}$. 

Similar arguments to [@lieb_hartree-fock_nodate] yield the appropriate norm constraint on the solution, and a simple application of the Rayleigh-Ritz principle (see [@reed_simon_4] theorem 13.6) yield infinitely many eigenvalues below 1 of the Dirac-Fock mean field operator (when restricted to $H$). 

Evidently, extending [@lieb_hartree-fock_nodate] to the Dirac-Fock case when restricted to $H$ is not terribly difficult. More challenging is the existence of critical points of $\mathcal{E}$ with no restriction of $\mathcal{E}$ to $H$, in which case one needs to deal with the unboundedness of $\mathcal{E}$. This is solved given suitable restrictions on $N$ and $Z$ in [@esteban_solutions_1999]. In any case, Kato's inequality allows one to very nicely extend the classical results of Lieb and Simon to the relativistic theory. 